### ISSUE TITLE
respect file arguments passed to `check/pytest_.py` in integration mode

### ISSUE THREAD

**Issue by richrines1** [SupertechLabs/applications-superstaq#80]
it would be nice if `check/pytest_.py --integration <file>_test.py` just ran `<file>_test.py`

**Comment by perlinm** [comment]
Clarification: what exactly do you want `check/pytest_.py --integration <file>_test.py` to do?  Run `<file>_test.py` and all `"*_integration_test.py"` files?

That is, are you basically asking for `--integration` to be an alias for "all `*_integration_test.py` files"?

**Comment by perlinm** [comment]
Discussed offline: the `--integration` flag should
1. always run `integration_setup()`, and
2. **iff** there are no file arguments, collect all `*integration_test.py` files

The fix is easy: [these lines](https://github.com/SupertechLabs/applications-superstaq/blob/fd170b1a4f1db0682795cabbec86682bb41f56c1/applications_superstaq/check/pytest_.py#L65-L69) should be replaced with
```python
        if files is None:
            files = check_utils.get_tracked_files(
                "*_integration_test.py", exclude=integration_exclude
            )
```
